// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaqd8qYGndoVe3HeScBN-4pOzI361gwhI',
    appId: '1:658097925901:web:46652a54b4863d88f78a44',
    messagingSenderId: '658097925901',
    projectId: 'flashcards-f5dbb',
    authDomain: 'flashcards-f5dbb.firebaseapp.com',
    storageBucket: 'flashcards-f5dbb.firebasestorage.app',
    databaseURL: 'https://flashcards-f5dbb-default-rtdb.firebaseio.com/',
    measurementId: 'G-KQ1M3Z3M0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoB5r4v1rpn1OAhRSMdTPACKyKtDXdEYE',
    appId: '1:658097925901:android:bd075ba124f8da83f78a44',
    messagingSenderId: '658097925901',
    projectId: 'flashcards-f5dbb',
    storageBucket: 'flashcards-f5dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNEWkcps_Qk1WE9dIcMYupevmrMneoG4k',
    appId: '1:658097925901:ios:0aa912d06e345330f78a44',
    messagingSenderId: '658097925901',
    projectId: 'flashcards-f5dbb',
    storageBucket: 'flashcards-f5dbb.firebasestorage.app',
    iosClientId: '658097925901-up5sorn1340cg3koraahontkc66f4rsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcards',
  );
}
